api: 
  url: https://apptwo.contrastsecurity.com/Contrast
  api_key: H6j5Z1vFjz58SShUq3bg5EW91Md19E5I
  service_key: ZTCIHQXE7OTKP5O2
  user_name: agent_a09a6314-c084-420c-b4fb-9b61794c3d0c@MarksFoo
agent: 
  logger: 
    stdout: true
  auto_update: false
  service: 
    enable: true
    logger: 
      path: contrast_service.log
      #level: ERROR
    host: 127.0.0.1
    port: 30555
